# Generated by Django 2.0.1 on 2018-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='book.Categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
